[package]
name = "ic-rand"
version = "0.1.2"
edition = "2021"


description = "simple random number generator for icp"
license = "MIT"

[dependencies]
candid = "0.10.10"
futures = "0.3.30"
ic-cdk = "0.16.0"
num-traits = "0.2.19"
